export const getMainFiles = () => [
  {
    path: 'src/pages/_app.tsx',
    content: `import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

const queryClient = new QueryClient()

export default function App({ Component, pageProps }: AppProps) {
  return (
    <QueryClientProvider client={queryClient}>
      <Component {...pageProps} />
    </QueryClientProvider>
  )
}`
  },
  {
    path: 'src/pages/index.tsx',
    content: `import { NextPage } from 'next'
import Head from 'next/head'
import { Layout } from '@/components/Layout'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next.js App</title>
        <meta name="description" content="Generated by Project Architect" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1 className="text-4xl font-bold mb-4">
          Welcome to Next.js
        </h1>
      </Layout>
    </>
  )
}

export default Home`
  }
];